apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bank-application
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/kaluifekwe/kubernetes-manifest-bank_app.git
    targetRevision: main
    path: bank-project
  
  destination:
    server: https://kubernetes.default.svc
    namespace: bank-app
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
